### ISSUE TITLE
Build failure with latest dependencies

### ISSUE THREAD

**Issue by snoyberg** [ch1bo/servant-exceptions#1]
```
Building library for servant-exceptions-0.1.0..
[1 of 1] Compiling Servant.Exception ( src/Servant/Exception.hs, dist/build/Servant/Exception.o )

src/Servant/Exception.hs:63:10: warning: [-Wmissing-methods]
    • No explicit implementation for
        ‘hoistServerWithContext’
    • In the instance declaration for
        ‘HasServer (Throws e :> Verb mt st ct a) context’
   |
63 | instance ( Exception e
   |          ^^^^^^^^^^^^^...

src/Servant/Exception.hs:89:10: warning: [-Wmissing-methods]
    • No explicit implementation for
        ‘hoistServerWithContext’
    • In the instance declaration for
        ‘HasServer (Throws e :> (api :> upstream)) context’
   |
89 | instance HasServer (api :> Throws e :> upstream) context =>
   |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...

src/Servant/Exception.hs:98:10: warning: [-Wmissing-methods]
    • No explicit implementation for
        ‘hoistServerWithContext’
    • In the instance declaration for
        ‘HasServer (Throws e :> (api1 :<|> api2)) context’
   |
98 | instance HasServer (Throws e :> api1 :<|> Throws e :> api2) context =>
   |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
Preprocessing executable 'example' for servant-exceptions-0.1.0..
Building executable 'example' for servant-exceptions-0.1.0..
[1 of 1] Compiling Main             ( example/Main.hs, dist/build/example/example-tmp/Main.o )

example/Main.hs:100:7: error:
    Not in scope: type constructor or class ‘:~>’
    Perhaps you meant ‘:>’ (imported from Servant)
    |
100 | nt :: IO :~> Handler
    |       ^^^^^^^^^^^^^^
```

**Comment by ch1bo** [comment]
What is the usual course of action when dependent APIs change? In this case `servant-0.12` was changed. If I fix this and release as new version now to work with 0.12 for stackage nightly, will this still work for stackage lts?

**Comment by snoyberg** [comment]
If you release with a new major version: LTS Haskell will automatically continue using the old version. If you release with a minor version bump but add a lower bound: we'll get a notification when trying to build the next LTS and manually tell it to use the old version. If you want to support both versions simultaneously: use CPP conditionals within your code.

**Comment by ch1bo** [comment]
Should be solved with 9947e5c537911326408bd6d904addca7d30bdf4f released as 0.1.1
